"""empty message

Revision ID: 249ea132313c
Revises: c02cd91d6830
Create Date: 2022-09-20 00:22:43.694606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249ea132313c'
down_revision = 'c02cd91d6830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=360), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('fname', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('lname', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
