"""empty message

Revision ID: 6400212cd58d
Revises: fe27c072e1fa
Create Date: 2022-09-20 22:27:40.341279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6400212cd58d'
down_revision = 'fe27c072e1fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sched_notifications', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sched_notifications', 'run_method',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sched_notifications', 'run_method',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('sched_notifications', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
