"""empty message

Revision ID: 7508fee001a2
Revises: ded2b78a6476
Create Date: 2022-09-20 22:16:16.913789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7508fee001a2'
down_revision = 'ded2b78a6476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sched_notifications', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('sched_notifications', 'run_method',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sched_notifications', 'run_method',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('sched_notifications', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
