"""empty message

Revision ID: 802581c6a554
Revises: 6400212cd58d
Create Date: 2022-09-20 22:55:11.044625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '802581c6a554'
down_revision = '6400212cd58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sched_notifications', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sched_notifications', 'run_method',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sched_notifications', 'run_method',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('sched_notifications', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
