"""empty message

Revision ID: fe27c072e1fa
Revises: 7508fee001a2
Create Date: 2022-09-20 22:22:46.698048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe27c072e1fa'
down_revision = '7508fee001a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sched_notifications', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('sched_notifications', 'run_method',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sched_notifications', 'run_method',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('sched_notifications', 'start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
